export class SharedModulesModuleConfiguration {
  public static ignoreColumns = [`UserId`];
  public static cannotEditColumns = [
    `_id`,
    `BirthDate`,
    `EmployeeNumber`,
    `DateTerminated`,
    `GenderId`,
    `IsTerminated`,
    `MaximumHoursAllocated`,
    `UserId`,
    `EmployeeClientSupplierId`,
    `DateLastLoggedIn`,
    `CreatedBy`,
    `DateCreated`,
    `ModifiedBy`,
    `DateModified`,
    // `StatusId`,
    `SessionToken`,
    `ParentTaskId`,
  ];
  public static optionalColumns = [
    `VATNumber`,
    `IsAdmin`,
    `IsLocked`,
    `IsActive`,
  ];
  public static checkboxColumns = [
    `CanCreate`,
    `CanDelete`,
    `CanEdit`,
    `CanView`,
    `IsActive`,
    `IsAdmin`,
    `IsAllDayEvent`,
    `IsLocked`,
    `IsTerminated`,
    `IsTransactionSuccessful`,
    `UseEmailAddress`,
    `UseHomeTelephoneNumber`,
    `UseMobileTelephoneNumber`,
    `UseOfficeTelephoneNumber`,
    `UsePostalAddress`,
  ];
  public static dateColumns = [
    `BirthDate`,
    `DateCreated`,
    `DateHired`,
    `DateLastLoggedIn`,
    `DateModified`,
    `DateTerminated`,
    `EndDate`,
    `StartDate`,
  ];
  public static timeColumns = [`EndTime`, `StartTime`];
  public static numberColumns = [
    `AccountNumber`,
    `Amount`,
    `EmployeeClientSupplierId`,
    `HomeTelephoneNumber`,
    `HoursWorked`,
    `IdNumber`,
    `MaximumHoursAllocated`,
    `MobileTelephoneNumber`,
    `OfficeTelephoneNumber`,
    `PostalCode`,
    `VATNumber`,
  ];
  public static maskedColumns = [`Password`, `ConfirmPassword`];
  public static textAreaColumns = [`Description`, `Summary`];
  public static useBreakNewlineSectionColumns = [`Break`, `Newline`, `Section`];
  public static referenceValueColumns = [
    `AssigneeId`,
    `ClientId`,
    `EmployeeId`,
    `EntityId`,
    `LookupCategoryId`,
    `ManagerId`,
    `MenuItemId`,
    `ProjectId`,
    `SupplierId`,
    `TaskId`,
    `UserGroupId`,
    `UserId`,
  ];
  public static lookupValueColumns = [
    `BankId`,
    `BudgetCodeId`,
    `CapacityId`,
    `CountryId`,
    `DepartmentId`,
    `EmploymentTypeId`,
    `GenderId`,
    `GroupId`,
    `IndustryTypeId`,
    `PositionId`,
    `PreferredLanguageId`,
    `PriorityId`,
    `ProjectAssignmentTypeId`,
    `ProjectTypeId`,
    `ProvinceId`,
    `SalutationId`,
    `ScheduleTypeId`,
    `StatusId`,
    `TaskTypeId`,
    `TransactionTypeId`,
    `UserLockReasonId`,
    `UserTypeId`,
    `WageTypeId`,
  ];
  public static useIconColumns = [
    `GenderId`,
    `GroupId`,
    `PriorityId`,
    `ProjectTypeId`,
    `StatusId`,
    `TaskTypeId`,
    `UserTypeId`,
  ];
  public static useImageColumns = [`BankId`, `Avatar`];
  public static selectControlTypeNames = [`lookupValue`, `referenceValue`];
  public static scheduleTimes = [
    '00:00:00',
    '00:30:00',
    '01:00:00',
    '01:30:00',
    '02:00:00',
    '02:30:00',
    '03:00:00',
    '03:30:00',
    '04:00:00',
    '04:30:00',
    '05:00:00',
    '05:30:00',
    '06:00:00',
    '06:30:00',
    '07:00:00',
    '07:30:00',
    '08:00:00',
    '08:30:00',
    '09:00:00',
    '09:30:00',
    '10:00:00',
    '10:30:00',
    '11:00:00',
    '11:30:00',
    '12:00:00',
    '12:30:00',
    '13:00:00',
    '13:30:00',
    '14:00:00',
    '14:30:00',
    '15:00:00',
    '15:30:00',
    '16:00:00',
    '16:30:00',
    '17:00:00',
    '17:30:00',
    '18:00:00',
    '18:30:00',
    '19:00:00',
    '19:30:00',
    '20:00:00',
    '20:30:00',
    '21:00:00',
    '21:30:00',
    '22:00:00',
    '22:30:00',
    '23:00:00',
    '23:30:00',
  ];
}
